Update check.yml

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -10,7 +10,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Check 1 files
+      - name: Check screencap-workspace-gdf.png
         id: check_1_files
         uses: andstor/file-existence-action@v1
         with:
@@ -22,7 +22,7 @@ jobs:
           echo Required file, 'screencap-workspace-gdf.png', is missing
           exit 1
           
-      - name: Check 2 files
+      - name: Check screencap-gdf-dist.png
         id: check_2_files
         uses: andstor/file-existence-action@v1
         with:
@@ -34,7 +34,7 @@ jobs:
           echo Required file, 'screencap-gdf-dist.png', is missing
           exit 1
           
-      - name: Check 3 files
+      - name: Check screencap-gdf-centroids.png
         id: check_3_files
         uses: andstor/file-existence-action@v1
         with:
@@ -45,7 +45,8 @@ jobs:
         run: |
           echo Required file, 'screencap-gdf-centroids.png', is missing
           exit 1
-      - name: Check 4 files
+          
+      - name: Check screencap-gdf-buffered-centroid.png
         id: check_4_files
         uses: andstor/file-existence-action@v1
         with:
@@ -55,5 +56,17 @@ jobs:
         if: steps.check_4_files.outputs.files_exists != 'true'
         run: |
           echo Required file, 'screencap-gdf-buffered-centroid.png', is missing
+          exit 1
+          
+      - name: Check assignment.ipynb
+        id: check_5_files
+        uses: andstor/file-existence-action@v1
+        with:
+          files: "assignment.ipynb"
+
+      - name: Required files exist
+        if: steps.check_5_files.outputs.files_exists != 'true'
+        run: |
+          echo Required file, 'assignment.ipynb', is missing
           exit 1
           
